/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RentWatchEscrow } from './RentWatchEscrow.js';
export * as factories from './factories/index.js';
export { RentWatchEscrow__factory } from './factories/RentWatchEscrow__factory.js';