/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface RentWatchEscrowInterface extends Interface {
    getFunction(nameOrSignature: "getRecord" | "lock" | "records" | "refund" | "release"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "PaymentLocked" | "PaymentRefunded" | "PaymentReleased"): EventFragment;

    encodeFunctionData(functionFragment: 'getRecord', values: [string]): string;
encodeFunctionData(functionFragment: 'lock', values: [string, BytesLike]): string;
encodeFunctionData(functionFragment: 'records', values: [string]): string;
encodeFunctionData(functionFragment: 'refund', values: [string]): string;
encodeFunctionData(functionFragment: 'release', values: [string]): string;

    decodeFunctionResult(functionFragment: 'getRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lock', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'records', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'release', data: BytesLike): Result;
  }

  
    export namespace PaymentLockedEvent {
      export type InputTuple = [leaseId: string, dataHash: BytesLike, timestamp: BigNumberish];
      export type OutputTuple = [leaseId: string, dataHash: string, timestamp: bigint];
      export interface OutputObject {leaseId: string, dataHash: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PaymentRefundedEvent {
      export type InputTuple = [leaseId: string, timestamp: BigNumberish];
      export type OutputTuple = [leaseId: string, timestamp: bigint];
      export interface OutputObject {leaseId: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PaymentReleasedEvent {
      export type InputTuple = [leaseId: string, timestamp: BigNumberish];
      export type OutputTuple = [leaseId: string, timestamp: bigint];
      export interface OutputObject {leaseId: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface RentWatchEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): RentWatchEscrow;
    waitForDeployment(): Promise<this>;

    interface: RentWatchEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getRecord: TypedContractMethod<
      [leaseId: string, ],
      [[string, bigint, string, boolean]],
      'view'
    >
    

    
    lock: TypedContractMethod<
      [leaseId: string, dataHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    records: TypedContractMethod<
      [arg0: string, ],
      [[string, bigint, string, boolean] & {dataHash: string, timestamp: bigint, lockedBy: string, released: boolean }],
      'view'
    >
    

    
    refund: TypedContractMethod<
      [leaseId: string, ],
      [void],
      'nonpayable'
    >
    

    
    release: TypedContractMethod<
      [leaseId: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getRecord'): TypedContractMethod<
      [leaseId: string, ],
      [[string, bigint, string, boolean]],
      'view'
    >;
getFunction(nameOrSignature: 'lock'): TypedContractMethod<
      [leaseId: string, dataHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'records'): TypedContractMethod<
      [arg0: string, ],
      [[string, bigint, string, boolean] & {dataHash: string, timestamp: bigint, lockedBy: string, released: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'refund'): TypedContractMethod<
      [leaseId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'release'): TypedContractMethod<
      [leaseId: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'PaymentLocked'): TypedContractEvent<PaymentLockedEvent.InputTuple, PaymentLockedEvent.OutputTuple, PaymentLockedEvent.OutputObject>;
getEvent(key: 'PaymentRefunded'): TypedContractEvent<PaymentRefundedEvent.InputTuple, PaymentRefundedEvent.OutputTuple, PaymentRefundedEvent.OutputObject>;
getEvent(key: 'PaymentReleased'): TypedContractEvent<PaymentReleasedEvent.InputTuple, PaymentReleasedEvent.OutputTuple, PaymentReleasedEvent.OutputObject>;

    filters: {
      
      'PaymentLocked(string,bytes32,uint256)': TypedContractEvent<PaymentLockedEvent.InputTuple, PaymentLockedEvent.OutputTuple, PaymentLockedEvent.OutputObject>;
      PaymentLocked: TypedContractEvent<PaymentLockedEvent.InputTuple, PaymentLockedEvent.OutputTuple, PaymentLockedEvent.OutputObject>;
    

      'PaymentRefunded(string,uint256)': TypedContractEvent<PaymentRefundedEvent.InputTuple, PaymentRefundedEvent.OutputTuple, PaymentRefundedEvent.OutputObject>;
      PaymentRefunded: TypedContractEvent<PaymentRefundedEvent.InputTuple, PaymentRefundedEvent.OutputTuple, PaymentRefundedEvent.OutputObject>;
    

      'PaymentReleased(string,uint256)': TypedContractEvent<PaymentReleasedEvent.InputTuple, PaymentReleasedEvent.OutputTuple, PaymentReleasedEvent.OutputObject>;
      PaymentReleased: TypedContractEvent<PaymentReleasedEvent.InputTuple, PaymentReleasedEvent.OutputTuple, PaymentReleasedEvent.OutputObject>;
    
    };
  }