/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface RentWatchEscrowInterface extends Interface {
    getFunction(nameOrSignature: "getRecord" | "lock" | "owner" | "records"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "PaymentLocked"): EventFragment;

    encodeFunctionData(functionFragment: 'getRecord', values: [string]): string;
encodeFunctionData(functionFragment: 'lock', values: [string, string, BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'records', values: [string]): string;

    decodeFunctionResult(functionFragment: 'getRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lock', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'records', data: BytesLike): Result;
  }

  
    export namespace PaymentLockedEvent {
      export type InputTuple = [paymentId: string, leaseId: string, dataHash: BytesLike, timestamp: BigNumberish];
      export type OutputTuple = [paymentId: string, leaseId: string, dataHash: string, timestamp: bigint];
      export interface OutputObject {paymentId: string, leaseId: string, dataHash: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface RentWatchEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): RentWatchEscrow;
    waitForDeployment(): Promise<this>;

    interface: RentWatchEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getRecord: TypedContractMethod<
      [paymentId: string, ],
      [[string, bigint, string]],
      'view'
    >
    

    
    lock: TypedContractMethod<
      [paymentId: string, leaseId: string, dataHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    records: TypedContractMethod<
      [arg0: string, ],
      [[string, bigint, string] & {dataHash: string, timestamp: bigint, lockedBy: string }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getRecord'): TypedContractMethod<
      [paymentId: string, ],
      [[string, bigint, string]],
      'view'
    >;
getFunction(nameOrSignature: 'lock'): TypedContractMethod<
      [paymentId: string, leaseId: string, dataHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'records'): TypedContractMethod<
      [arg0: string, ],
      [[string, bigint, string] & {dataHash: string, timestamp: bigint, lockedBy: string }],
      'view'
    >;

    getEvent(key: 'PaymentLocked'): TypedContractEvent<PaymentLockedEvent.InputTuple, PaymentLockedEvent.OutputTuple, PaymentLockedEvent.OutputObject>;

    filters: {
      
      'PaymentLocked(string,string,bytes32,uint256)': TypedContractEvent<PaymentLockedEvent.InputTuple, PaymentLockedEvent.OutputTuple, PaymentLockedEvent.OutputObject>;
      PaymentLocked: TypedContractEvent<PaymentLockedEvent.InputTuple, PaymentLockedEvent.OutputTuple, PaymentLockedEvent.OutputObject>;
    
    };
  }